---
# tasks file for heimdall

- name: install heimdall pacakges and heimdall profile
  shell: curl -L https://raw.githubusercontent.com/maticnetwork/install/heimdall-v2/heimdall-v2.sh | bash -s -- {{ heimdall_version }} {{ network }} {{ node_type }}
  become: true

- name: update heimdall inbound peers
  ansible.builtin.lineinfile:
    path: /var/lib/heimdall/config/config.toml
    regexp: '^max_num_inbound_peers =.*$'
    line: 'max_num_inbound_peers = 100'
    backrefs: yes
  when: node_type == "sentry" or "archive"
  become: true

- name: update heimdall outbound peers
  ansible.builtin.lineinfile:
    path: /var/lib/heimdall/config/config.toml
    regexp: '^max_num_outbound_peers =.*$'
    line: 'max_num_outbound_peers = 100'
    backrefs: yes
  when: node_type == "sentry" or "archive"
  become: true

- name: update heimdall inbound peers
  ansible.builtin.lineinfile:
    path: /var/lib/heimdall/config/config.toml
    regexp: '^max_num_inbound_peers =.*$'
    line: 'max_num_inbound_peers = 100'
    backrefs: yes
  when: node_type == "validator"
  become: true

- name: update heimdall outbound peers
  ansible.builtin.lineinfile:
    path: /var/lib/heimdall/config/config.toml
    regexp: '^max_num_outbound_peers =.*$'
    line: 'max_num_outbound_peers = 100'
    backrefs: yes
  when: node_type == "validator"
  become: true

- name: update heimdall inbound peers
  ansible.builtin.lineinfile:
    path: /var/lib/heimdall/config/config.toml
    regexp: '^max_num_inbound_peers =.*$'
    line: 'max_num_inbound_peers = 200'
    backrefs: yes
  when: node_type == "bootnode"
  become: true

- name: update heimdall outbound peers
  ansible.builtin.lineinfile:
    path: /var/lib/heimdall/config/config.toml
    regexp: '^max_num_outbound_peers =.*$'
    line: 'max_num_outbound_peers = 200'
    backrefs: yes
  when: node_type == "bootnode"
  become: true

- name: update heimdall external address
  ansible.builtin.lineinfile:
    path: /var/lib/heimdall/config/config.toml
    regexp: '^external_address =.*$'
    line: 'external_address = "{{ ansible_host }}:26656"'
    backrefs: yes
  when: node_type == "sentry" or "archive" or "bootnode"
  become: true

- name: update heimdall external address
  ansible.builtin.lineinfile:
    path: /var/lib/heimdall/config/config.toml
    regexp: '^external_address =.*$'
    line: 'external_address = ""'
    backrefs: yes
  when: node_type == "validator"
  become: true

- name: start Heimdall service
  systemd:
    state: restarted
    daemon-reload: yes
    name: heimdalld.service
  become: yes