---
# tasks file for bor

- name: install bor pacakges and bor profile
  shell: curl -L https://raw.githubusercontent.com/maticnetwork/install/main/bor.sh | bash -s -- {{ bor_version }} {{ network }} {{ node_type }}
  become: true

- name: uncomment p2p discovery
  shell: sed -i 's|.*\[p2p.discovery\]|  \[p2p.discovery\] |g' /var/lib/bor/config.toml
  become: true

- name: make bor the user of data directory
  shell: chown bor /var/lib/bor
  become: true

- name: add values to the maxpeers value
  ansible.builtin.lineinfile:
    path: /var/lib/bor/config.toml
    regexp: '^\s*maxpeers =.*$'
    line: '\t maxpeers = 200'
    backrefs: yes
  when: node_type == "sentry" or "archive"
  become: true

- name: add values to the max peers value
  ansible.builtin.lineinfile:
    path: /var/lib/bor/config.toml
    regexp: '^\s*maxpeers =.*$'
    line: '\t maxpeers = 20'
    backrefs: yes
  when: node_type == "validator"
  become: true

- name: add values for max peers for bootnode
  ansible.builtin.lineinfile:
    path: /var/lib/bor/config.toml
    regexp: '^\s*maxpeers =.*$'
    line: '\t maxpeers = 200'
    backrefs: yes
  when: node_type == "bootnode"
  become: true

- name: start bor service
  systemd:
    state: restarted
    daemon-reload: yes
    name: bor.service
  become: true