
#how to run this
#ansible-playbook --connection=local --inventory 127.0.0.1, --limit 127.0.0.1  playbooks/make_node.yml


- name: Create Sentry node
  hosts: localhost
  connection: local 
  tasks:
    - name: Make a new node
      include_role:
        name: roles/create-node
        apply:
          tags: always
      tags:
        - create_node

    - name: add new node into runtime inventory
      add_host:
        name: remote-host 
        groups: web
        ansible_host: "{{public_ip}}"

- name: test
  hosts: remote-host
  remote_user: ubuntu
  become: true
  vars:
    # ansible_python_interpreter: /home/graphicaldot/Programs/Matic/node-ansible/bin/python3
    ansible_ssh_private_key_file: ~/Downloads/PemFiles/mainnet-v1-1.pem
    ansible_connection: ssh
    ansible_ssh_user: ubuntu

  tasks:
    - name: Install Ngeinx
      package:
        name: nginx
        state: present


- name: Install Heimdall
  hosts: remote-host
  remote_user: ubuntu
  become: true

  roles:
    - role: roles/install-dependencies
    - role: roles/install-heimdall
  # tasks:
  #     - name: print info
  #       debug:
  #         msg: "Host full name is {{ inventory_hostname }}. Short name is {{ inventory_hostname_short }}"



# - name: Attach EBS
#   hosts: localhost
#   connection: local 
#   tasks:
#     - name: Attch ebs
#       include_role:
#         name: roles/attach-snapshots
#         apply:
#           tags: always
#       tags:
#         - snapshots




# - name: run playbook playbook2
#   import_playbook: network.yml
#   vars:
#     hosts: "{{public_ip}}"

    # - name: Install dependencies
    #   include_role:
    #     name: roles/install-dependencies
    #     apply:
    #       tags: always
    #   tags:
    #     - install_dependencies

    # - name: Build Heimdall
    #   include_role:
    #     name: roles/install-heimdall
    #     apply:
    #       tags: always
    #   tags:
    #     - build

    # - name: Build Bor
    #   include_role:
    #     name: roles/install-bor
    #     apply:
    #       tags: always
    #   tags:
    #     - build

    # - name: Setup and deploy network
    #   include_role:
    #     name: roles/setup-network
    #     apply:
    #       tags: always
    #   tags:
    #     - deploy
