





- name: Creating a Sentry Node
  community.aws.ec2_instance:
    name: "{{name}}"
    key_name: "{{key_pair_name}}"
    instance_type: "{{instance_type}}"
    region: "{{aws_region}}"
    ebs_optimized: yes
    detailed_monitoring: yes
    security_groups: "{{vpc_security_group}}"
    network: 
      assign_public_ip: true
    vpc_subnet_id: "{{ vpc_subnet_id}}" 

    image_id: "{{ami_id}}"
    instance_role: "{{instance_iam_role}}"
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: 200
          volume_type: gp3

    tags:
      Network: "{{network}}"
    state: present
    filters: 
       "tag:Name": "{{name}}"
  register: instance

- set_fact: 
    instance_id: "{{instance.instance_ids[0]}}"


- set_fact:
    public_ip: "{{instance.instances[0].public_ip_address}}"






